name: PHP Linting
on: 
    pull_request:
        branches:
            - master
            - staging
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: michaelw90/PHP-Lint@master
